/*
Structure of resource block
<block> <parameters> {
    key1 = value1
    key2 = value2
}

*/

# Type of block: resource
# resource type: "local_file", where local=provider, file=resource
# resource name: "pet", logical name
# filename, content are arguments
resource "local_file" "pet" {
    filename = var.filename
    content = "My favorite pet is ${random_pet.my-pet.id}"
    # Explicit Dependency
    depends_on = [
      random_pet.my-pet
    ]
}

resource "random_pet" "my-pet" {
    prefix = var.prefix
    separator = var.separator
    length = var.length
}


resource "local_file" "map-test" {
  filename = "data_out/map_test.txt"
  content = var.file-content["statement2"]
}

resource "local_file" "lifecycle" {
    filename = "data_out/lifecycle.txt"
    content = "My favorite pet is ${random_pet.my-pet.id}"
    # Explicit Dependency
    depends_on = [
      random_pet.my-pet
    ]
    lifecycle {
      create_before_destroy = true
    }
}

resource "local_file" "data_source" {
    filename = "data_out/dog_source.txt"
    content = data.local_file.dog_source.content
}

data "local_file" "dog_source" {
  filename = "./data_in/dog.txt"
}

output pet-name {
  value = random_pet.my-pet
  description = "Record the value of Pet Id generated by the random_pet resource"
}




